[default_session]
preview_command = "eza --all --git --icons --color=always {}"

[[session]]
name = "Dotfiles"
path = "~/dotfiles"
startup_command = "nvim"
windows = ["shell"]

[[session]]
name = "Downloads 📥"
path = "~/Downloads"
startup_command = "eza"

[[session]]
name = "tmp"
path = "~/"

[[window]]
name = "neovim"
startup_script = "nvim"

[[window]]
name = "shell"
startup_script = "eza --all --git --icons --color=always"
