[tool.poetry]
name = "dotfiles"
version = "0.1.0"
description = ""
authors = ["Zahid Kizmaz <tech@zahid.rocks>"]

[tool.poetry.dependencies]
python = "^3.10"
pynvim = "^0.4.3"
python-lsp-server = {version = "^1.3.3", extras = ["all"]}

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
