[bar.default]
capsule = true
center = ["group:g1"]
end = [
  "keyboard_layout",
  "group:g3",
  "volume",
  "brightness",
  "caffeine",
  "power_profile",
  "battery",
  "session",
]
font_weight = 600
margin_edge = 2.0
margin_ends = 0.0
padding = 0
scale = 1.5
shadow = false
start = ["workspaces", "active_window", "media"]
widget_spacing = 12

[[bar.default.capsule_group]]
fill = "surface_variant"
id = "g1"
members = ["control-center", "clock"]
opacity = 1.0
padding = 6.0

[[bar.default.capsule_group]]
fill = "surface_variant"
id = "g2"
members = ["keyboard_layout", "tray", "network", "bluetooth"]
opacity = 1.0
padding = 6.0

[[bar.default.capsule_group]]
fill = "surface_variant"
id = "g3"
members = ["tray", "network", "bluetooth"]
opacity = 1.0
padding = 6.0

[desktop_widgets]
schema_version = 1
widget_order = []

[desktop_widgets.grid]
cell_size = 16
major_interval = 4
visible = true

[desktop_widgets.widget]

[hooks]
battery_charging = "powerprofilesctl set performance"
battery_discharging = "powerprofilesctl set power-saver"

[idle]
behavior_order = ["Dim Screen", "lock", "screen-off", "Suspend & Hibernate"]

[idle.behavior."Dim Screen"]
action = "command"
command = "ibrightnessctl -s set 5"
enabled = true
resume_command = "brightnessctl -r"
timeout = 120

[idle.behavior."Suspend & Hibernate"]
action = "command"
command = "systemctl suspend-then-hibernate"
enabled = true
timeout = 600

[idle.behavior.lock]
action = "lock"
enabled = true
timeout = 300

[idle.behavior.screen-off]
action = "screen_off"
enabled = true
timeout = 380

[location]
address = "Berlin, DE"

[lockscreen]
wallpaper = "/home/zahid/dotfiles/noctalia/.local/state/noctalia/lock-screen-bg.png"

[lockscreen_widgets]
enabled = true
schema_version = 1
widget_order = [
  "lockscreen-login-box@eDP-1",
  "lockscreen-widget-0000000000000001",
  "lockscreen-widget-0000000000000002",
  "lockscreen-widget-0000000000000003",
]

[lockscreen_widgets.grid]
cell_size = 16
major_interval = 4
visible = true

[lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
box_height = 0.0
box_width = 0.0
cx = 1128.0
cy = 1216.0
output = "eDP-1"
rotation = 0.0
type = "login_box"

[lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
show_login_button = true

[lockscreen_widgets.widget.lockscreen-widget-0000000000000001]
box_height = 208.0
box_width = 416.0
cx = 1128.0
cy = 248.0
output = "eDP-1"
rotation = -0.0
type = "clock"

[lockscreen_widgets.widget.lockscreen-widget-0000000000000001.settings]
background = false

[lockscreen_widgets.widget.lockscreen-widget-0000000000000002]
box_height = 64.0
box_width = 816.0
cx = 1128.0
cy = 384.0
output = "eDP-1"
rotation = 0.0
type = "clock"

[lockscreen_widgets.widget.lockscreen-widget-0000000000000002.settings]
background = false
format = "%A %d %B %Y"

[lockscreen_widgets.widget.lockscreen-widget-0000000000000003]
box_height = 384.0
box_width = 320.0
cx = 2072.0
cy = 0.0
output = "eDP-1"
rotation = 0.0
type = "media_player"

[lockscreen_widgets.widget.lockscreen-widget-0000000000000003.settings]
background = false
background_padding = 11.0
hide_when_no_media = true
layout = "vertical"

[nightlight]
enabled = true

[[plugins.source]]
kind = "git"
location = "https://github.com/noctalia-dev/community-plugins"
name = "community"

[[plugins.source]]
kind = "git"
location = "https://github.com/noctalia-dev/official-plugins"
name = "official"

[shell]
clipboard_enabled = false
font_family = "Arimo Nerd Font Propo"
polkit_agent = true
telemetry_enabled = false
ui_scale = 1.5

[shell.animation]
enabled = false

[[shell.session.actions]]
action = "lock"
enabled = false
shortcut = "1"
variant = "default"

[[shell.session.actions]]
action = "logout"
enabled = true
shortcut = "2"
variant = "default"

[[shell.session.actions]]
action = "lock_and_suspend"
enabled = true
shortcut = "3"
variant = "default"

[[shell.session.actions]]
action = "reboot"
enabled = true
shortcut = "4"
variant = "default"

[[shell.session.actions]]
action = "shutdown"
enabled = true
shortcut = "5"
variant = "destructive"

[shell.shadow]
blur = 0

[theme]
builtin = "Catppuccin"
source = "builtin"

[wallpaper]
enabled = false

[weather]
auto_locate = true

[widget.brightness]
scroll_step = 1

[widget.clock]
format = "{:%a %d %b %H:%M}"
tooltip_format = "{:%A %x}"

[widget.control-center]
glyph = "home"

[widget.media]
hide_when_no_media = true

[widget.network]
show_label = false

[widget.volume]
scroll_step = 1
