#!/usr/bin/env bash

#------------------------------
# Aliases
#------------------------------
alias nv='nvim'
alias mkdir='mkdir -v'
alias pls='sudo $(fc -ln -1)'
alias grep='grep --colour=auto'

#------------------------------
# LS Aliases
#------------------------------
alias ls='ls --color=auto -h -F '
alias ll='ls --color=auto -h -F -l '
alias la='ls --color=auto -h -F -a '

#------------------------------
# Git Aliases
#------------------------------
alias gs="git status -sb"
alias gp='git pull origin $(git branch --show-current)'
alias grc='git pull --rebase origin $(git branch --show-current)'
alias gP="git push"
alias ga="git add "
alias gA="git add -A"
alias gc="git commit "
alias gl="git log"
alias gf="git fetch --all"
alias gco="git checkout "
alias gd="git diff"
alias gdc='git diff --cached'
alias gm="git commit -m "
alias gfrb="git fetch origin && git rebase origin/master"
alias gsh='git stash '
alias gmno='git commit --amend --no-edit'
alias gmo='git merge origin/master'
alias gfgp='git fetch origin && git pull origin '
alias 'git wipe'='git reset --hard HEAD '

#------------------------------
# GitHub CLI Aliases
#------------------------------
alias pro="gh pr view --web"
