#!/bin/sh

#------------------------------
# Aliases
#------------------------------
alias grep='grep --colour=auto'
alias mkdir='mkdir -v'
alias ls='ls --color=auto -h -F '
alias nv='nvimvenv'
alias nvim='nvimvenv'

#------------------------------
# Screen Aliases
#------------------------------
alias sls="screen -ls"
alias sr="screen -r "
alias sR="screen -D -RR " # Get screen no matter what
alias ss="screen -S "
alias sx="screen -XS "

#------------------------------
# Git Aliases
#------------------------------
alias gs="git status -sb"
alias gp="git push"
alias ga="git add "
alias gA="git add -A"
alias gc="git commit "
alias gl="git log"
alias gf="git fetch --all"
alias gco="git checkout "
alias gd="git diff "
alias gdc='git diff --cached'
alias gm="git commit -m "
alias gfrb="git fetch origin && git rebase origin/master"
alias gsh='git stash '
alias gmno='git commit --amend --no-edit'
alias gmo='git merge origin/master'
alias gpm='git pull origin $(git branch --show-current)'
alias gfgp='git fetch origin && git pull origin '
alias 'git wipe'='git reset --hard HEAD '

#------------------------------
# FZF Aliases
#------------------------------
export FD_OPTIONS="--hidden --follow"
export FZF_DEFAULT_OPTS="--no-hscroll --height 40% --layout=reverse --margin=0 --info=inline --preview-window=:noborder"
export FZF_DEFAULT_COMMAND="fd --type f --type l $FD_OPTIONS"
