version: 2
root-markers:
    - .git/
lint-debounce: 1s
log-file: /tmp/efm.log
log-level: 1

tools:
    yamllint: &yamllint
        prefix: yamllint
        lint-stdin: true
        lint-ignore-exit-code: true
        lint-command: yamllint -f parsable -

    shellcheck: &shellcheck
        prefix: shellcheck
        lint-stdin: true
        lint-ignore-exit-code: true
        lint-command: shellcheck --color=never --format=gcc -

    ansible_lint: &ansible-lint
        prefix: ansible-lint
        lint-stdin: true
        lint-command: ansible-lint --nocolor -

    gitcommit-gitlint: &gitcommit-gitlint
        lint-command: 'gitlint'
        lint-stdin: true
        lint-formats:
            - '%l: %m: "%r"'
            - '%l: %m'

    javascript-eslint: &javascript-eslint
        lint-command: "eslint -f visualstudio --stdin --stdin-filename ${INPUT}"
        lint-ignore-exit-code: true
        lint-stdin: true
        lint-formats:
            - "%f(%l,%c): %tarning %m"
            - "%f(%l,%c): %rror %m"

languages:
    ansible.yaml:
        - <<: *ansible-lint
    yaml:
        - <<: *yamllint
    sh:
        - <<: *shellcheck
    typescript:
        - <<: *javascript-eslint
    typescriptreact:
        - <<: *javascript-eslint
    javascript:
        - <<: *javascript-eslint
    javascriptreact:
        - <<: *javascript-eslint
    gitcommit:
        - <<: *gitcommit-gitlint
