#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &
setxkbmap -option caps:escape,shift:both_capslock &
"$HOME/.config/bspwm/autostart.sh" &

monitor_name=$(bspc query -M --names | head -1)
bspc monitor "$monitor_name" -d I II III IV V VI VII VIII IX

bspc config border_width 2
bspc config window_gap 10
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

# Currently doesn't work
bspc rule -a CopyQ state=floating
