#! /bin/sh

"$HOME/.config/bspwm/autostart.sh"

bspc monitor -d I II III IV V VI VII VIII IX

bspc config border_width 2
bspc config window_gap 4
bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config focused_border_color '#FAE3B0'
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

bspc rule -a copyq state=floating follow=on
bspc rule -a '*:*:Picture-in-Picture' state=floating follow=on sticky=on border=off # Firefox
bspc rule -a '*:*:Picture in picture' state=floating follow=on sticky=on border=off # Chromium based
