general {
    hide_cursor = false
}

auth {
    fingerprint {
        enabled = true
        ready_message = Scan fingerprint to unlock
        present_message = Scanning...
        retry_delay = 250 # in milliseconds
    }
}


##### UI
$wall = ~/.config/hypr/wallpapers/16.jpeg
$battery = ~/.config/hypr/scripts/battery.sh

animations {
    enabled = false
}

background {
    monitor =
    path = $wall
    blur_passes = 0 # 0 disables blurring
}

# Time
label {
    monitor =
    text = cmd[update:1000] echo "<span>$(date +"%H")</span>"
    color =rgb(240, 231, 219)
    font_size = 80
    font_family = JetBrains Mono Nerd Font Mono Bold
    position = -100, 400
    halign = center
    valign = center
}

# Time
label {
    monitor =
    text = cmd[update:1000] echo "<span>$(date +":%M")</span>"
    color = rgb(214, 209, 209)
    font_size = 80
    font_family = JetBrains Mono Nerd Font Mono Bold
    position = 55, 400
    halign = center
    valign = center
}

# Day-Month-Date
label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +"%A, %B %d")"
    color = rgb(200, 200, 200)
    font_size = 24
    font_family = JetBrains Mono Nerd Font Mono Bold
    position = -25, 330
    halign = center
    valign = center
}


# USER-BOX
shape {
    monitor =
    size = 250, 50
    color =rgba(231, 92, 92, 1)
    rounding = 15
    border_size = 0
    border_color = rgba(255, 255, 255, 1)
    rotate = 0
    xray = false # if true, make a "hole" in the background (rectangle of specified size, no rotation)
    position = -100, -250
    halign = right
    valign = center
}

# USER
label {
    monitor =
    text = cmd[update:60000] echo "<i> Good $(H=$(date +%H); if [ $H -lt 12 ]; then echo Morning; elif [ $H -lt 18 ]; then echo Afternoon; else echo Evening; fi) $(echo "${USER:0:1}" | tr '[:lower:]' '[:upper:]')$(echo "${USER:1}" | tr '[:upper:]' '[:lower:]') </i>"
    color = rgba(255, 255, 255, 0.8)
    outline_thickness = 0
    dots_size = 0.2 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.2 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    font_size = 14
    position = -110, -250
    halign = right
    valign = center
}

# INPUT FIELD
input-field {
    monitor =
    size = 250, 50
    outline_thickness = 0
    dots_size = 0.2 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.2 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    outer_color = rgba(255, 255, 255, 0)
    inner_color = rgba(231, 92, 92, 1)
    font_color = rgba(248, 248, 248, 1)
    fade_on_empty = false
    placeholder_text = <i><span foreground="##ffffff99">   Enter passwd</span></i>
    hide_input = false
    position = -100, -335
    halign = right
    valign = center
    rounding = 15
}
# Battery div
shape {
    monitor =
    size = 140, 80
    color =rgba(231, 92, 92, 1)
    # color =rgb(240, 170, 170)
    rounding = 20
    rotate = 0
    position = -40, -20
    halign = right
    valign = top
    zindex = 1
}

# Battery
label {
    monitor =
    text = cmd[update:1000] echo -e "$($battery)"
    color = rgb(255, 255, 255)
    font_size = 25
    font_family = JetBrains Mono Nerd Font Mono ExtraBold
    position = -60, -35
    halign = right
    valign = top
    zindex = 5
}
