-- Generated by nwg-displays on 2026-06-03 at 22:28:01. Do not edit manually.

hl.monitor({
  output = "desc:BOE 0x0BCA",
  mode = "2256x1504@60.0",
  position = "160x1440",
  scale = 1.0,
  bitdepth = 10,
})
