require('plugins.plugins')
require('plugins.onedark-plugin')
require('plugins.comp-plugin')
require('plugins.lspinstall-plugin')
require('plugins.treesitter-plugin')
require('plugins.telescope-plugin')
require('plugins.lightline-plugin')
