name: "Flake Build Systems"
on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    paths:
      - nixos/**
      - flake.nix
      - flake.lock
  pull_request:
    branches:
      - main
    paths:
      - nixos/**
      - flake.nix
      - flake.lock
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build NixOS system
        run: >
          nix build .#nixosConfigurations.fw13-amd.config.system.build.toplevel
