name: "Flake Check & Build"
on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: read
  actions: read
  checks: write

jobs:
  check:
    name: Flake check (all systems)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: DeterminateSystems/flakehub-cache-action@v9

      - uses: nicknovitski/nix-develop@v1

      - uses: j178/prek-action@v2

      - name: Check all systems
        run: nix flake check --all-systems

  build-x86_64-linux:
    name: Build x86_64-linux
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: DeterminateSystems/flakehub-cache-action@v9

      - name: Build x86_64-linux outputs
        run: |
          nix run nixpkgs#nix-fast-build -- \
            --flake . \
            --skip-cached \
            --no-nom \
            --systems x86_64-linux \
            --eval-workers 2 \
            --result-format junit \
            --result-file /tmp/nix-results.xml

      - name: Publish build results to PR
        if: failure()
        uses: dorny/test-reporter@v3
        with:
          name: Build results
          path: /tmp/nix-results.xml
          reporter: java-junit

      - name: Upload test results artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: nix-results-x86_64-linux
          path: /tmp/nix-results.xml
